/**
 * Paystack Service
 *
 * Wraps all Paystack REST API calls used by the escrow system.
 * This service is the ONLY place that talks to Paystack -- all other
 * services go through this layer.
 *
 * API reference: https://paystack.com/docs/api/
 *
 * Key conventions:
 *   - All amounts are in KES kobo (cents). 1 KES = 100 kobo.
 *   - Currency is always "KES" for the Kenyan market.
 *   - Auth: Bearer token using PAYSTACK_SECRET_KEY.
 *   - M-PESA recipients use bank_code "MPESA" in the Paystack API.
 */

import axios, { AxiosInstance, AxiosError } from "axios";

// ============================================================
// Types
// ============================================================

export interface InitPaymentParams {
    email: string;          // Buyer's email address
    amount: number;         // Amount in KES kobo (cents)
    reference: string;      // Unique payment reference (generated by caller)
    currency?: string;      // Defaults to "KES"
    channels?: string[];    // e.g. ["card", "mobile_money", "bank"]
    metadata?: Record<string, any>;
}

export interface InitPaymentResult {
    authorization_url: string;   // URL to redirect buyer to Paystack checkout
    access_code: string;         // Paystack checkout session code
    reference: string;           // Echoed back for verification
}

export interface PaystackTransaction {
    id: number;
    status: string;              // "success", "failed", "abandoned"
    reference: string;
    amount: number;              // Amount in kobo
    currency: string;
    paid_at: string;
    channel: string;
    customer: { email: string };
    metadata: Record<string, any> | null;
}

export interface PaystackTransfer {
    transfer_code: string;
    status: string;              // "pending", "success", "failed"
    reference: string;
    amount: number;
    currency: string;
    recipient: { recipient_code: string };
}

export interface PaystackBank {
    id: number;
    name: string;
    slug: string;
    code: string;
    country: string;
    currency: string;
    type: string;
}

export interface TransferParams {
    amount: number;              // Amount in KES kobo
    recipientCode: string;      // Paystack transfer recipient code (RCP_xxx)
    reference: string;           // Unique transfer reference
    reason: string;              // Human-readable reason for the transfer
}

export interface CreateRecipientParams {
    name: string;
    phoneNumber?: string;        // For M-PESA (e.g. "0712345678")
    accountNumber?: string;      // For bank transfers
    bankCode?: string;           // Paystack bank code
}

// ============================================================
// Service
// ============================================================

class PaystackService {
    private client: AxiosInstance;
    private secretKey: string;

    constructor() {
        this.secretKey = process.env.PAYSTACK_SECRET_KEY || "";
        this.client = axios.create({
            baseURL: "https://api.paystack.co",
            headers: {
                Authorization: `Bearer ${this.secretKey}`,
                "Content-Type": "application/json",
            },
        });
    }

    // ----------------------------------------------------------
    // Payments
    // ----------------------------------------------------------

    /**
     * Initialize a payment transaction on Paystack.
     *
     * Returns an authorization_url that the buyer should be redirected to.
     * After payment, the buyer (or webhook in Phase 2) calls verifyPayment()
     * to confirm the transaction.
     *
     * NOTE: We intentionally do NOT set callback_url in Phase 1.
     * The frontend handles the redirect generically.
     */
    async initializePayment(params: InitPaymentParams): Promise<InitPaymentResult> {
        const payload = {
            email: params.email,
            amount: params.amount,
            reference: params.reference,
            currency: params.currency || "KES",
            channels: params.channels || ["card", "mobile_money", "bank"],
            metadata: params.metadata || {},
        };

        const response = await this.makeRequest<{
            data: InitPaymentResult;
        }>("POST", "/transaction/initialize", payload);

        return response.data;
    }

    /**
     * Verify a payment transaction by its reference.
     *
     * This should be called after the buyer completes payment on the
     * Paystack checkout page. Returns the full transaction record,
     * including the status ("success" means payment was received).
     */
    async verifyPayment(reference: string): Promise<PaystackTransaction> {
        const response = await this.makeRequest<{
            data: PaystackTransaction;
        }>("GET", `/transaction/verify/${encodeURIComponent(reference)}`);

        return response.data;
    }

    // ----------------------------------------------------------
    // Transfer Recipients
    // ----------------------------------------------------------

    /**
     * Create an M-PESA transfer recipient on Paystack.
     *
     * M-PESA is the most common payout method for Kenyan creators.
     * Uses bank_code "MPESA" with the phone number as account_number.
     */
    async createMpesaRecipient(params: {
        name: string;
        phoneNumber: string;
    }): Promise<{ recipient_code: string }> {
        const payload = {
            type: "mobile_money",
            name: params.name,
            account_number: params.phoneNumber,
            bank_code: "MPESA",
            currency: "KES",
        };

        const response = await this.makeRequest<{
            data: { recipient_code: string };
        }>("POST", "/transferrecipient", payload);

        return { recipient_code: response.data.recipient_code };
    }

    /**
     * Create a bank transfer recipient on Paystack.
     */
    async createBankRecipient(params: {
        name: string;
        accountNumber: string;
        bankCode: string;
    }): Promise<{ recipient_code: string }> {
        const payload = {
            type: "nuban",
            name: params.name,
            account_number: params.accountNumber,
            bank_code: params.bankCode,
            currency: "KES",
        };

        const response = await this.makeRequest<{
            data: { recipient_code: string };
        }>("POST", "/transferrecipient", payload);

        return { recipient_code: response.data.recipient_code };
    }

    /**
     * Delete (deactivate) a transfer recipient on Paystack.
     */
    async deleteRecipient(recipientCode: string): Promise<void> {
        await this.makeRequest("DELETE", `/transferrecipient/${recipientCode}`);
    }

    // ----------------------------------------------------------
    // Transfers (Payouts)
    // ----------------------------------------------------------

    /**
     * Initiate a transfer (payout) to a seller's account.
     *
     * IMPORTANT: This should be called AFTER the database transaction
     * commits. If the transfer API call fails, the escrow should be
     * flagged for manual review -- the funds are still safe in the
     * Paystack balance.
     */
    async initiateTransfer(params: TransferParams): Promise<{
        transfer_code: string;
        status: string;
    }> {
        const payload = {
            source: "balance",
            amount: params.amount,
            recipient: params.recipientCode,
            reference: params.reference,
            reason: params.reason,
            currency: "KES",
        };

        const response = await this.makeRequest<{
            data: { transfer_code: string; status: string };
        }>("POST", "/transfer", payload);

        return {
            transfer_code: response.data.transfer_code,
            status: response.data.status,
        };
    }

    /**
     * Verify the status of a transfer by reference.
     */
    async verifyTransfer(reference: string): Promise<PaystackTransfer> {
        const response = await this.makeRequest<{
            data: PaystackTransfer;
        }>("GET", `/transfer/verify/${encodeURIComponent(reference)}`);

        return response.data;
    }

    // ----------------------------------------------------------
    // Refunds
    // ----------------------------------------------------------

    /**
     * Refund a transaction (partially or fully).
     *
     * The transaction is identified by the original payment reference.
     * If amount is less than the original, it is a partial refund.
     */
    async refundTransaction(params: {
        transactionReference: string;
        amount?: number;
    }): Promise<void> {
        const payload: Record<string, any> = {
            transaction: params.transactionReference,
        };

        if (params.amount) {
            payload.amount = params.amount;
        }

        await this.makeRequest("POST", "/refund", payload);
    }

    // ----------------------------------------------------------
    // Utilities
    // ----------------------------------------------------------

    /**
     * List all banks available for Kenya on Paystack.
     * Used when a seller is setting up bank payout details.
     */
    async listKenyaBanks(): Promise<PaystackBank[]> {
        const response = await this.makeRequest<{
            data: PaystackBank[];
        }>("GET", "/bank?country=kenya&currency=KES");

        return response.data;
    }

    /**
     * Resolve (verify) a bank account number.
     * Returns the account holder's name as registered with the bank.
     */
    async resolveAccountNumber(params: {
        accountNumber: string;
        bankCode: string;
    }): Promise<{ account_name: string }> {
        const response = await this.makeRequest<{
            data: { account_name: string };
        }>(
            "GET",
            `/bank/resolve?account_number=${params.accountNumber}&bank_code=${params.bankCode}`
        );

        return { account_name: response.data.account_name };
    }

    /**
     * Get the current Paystack balance.
     * Useful for admin dashboards and health checks.
     */
    async getBalance(): Promise<{ currency: string; balance: number }[]> {
        const response = await this.makeRequest<{
            data: { currency: string; balance: number }[];
        }>("GET", "/balance");

        return response.data;
    }

    // ----------------------------------------------------------
    // Internal helper
    // ----------------------------------------------------------

    /**
     * Centralized HTTP request handler with consistent error formatting.
     *
     * All Paystack API errors are caught here and re-thrown with
     * a descriptive message that includes the Paystack error detail.
     */
    private async makeRequest<T>(
        method: "GET" | "POST" | "PUT" | "DELETE",
        path: string,
        data?: Record<string, any>
    ): Promise<T> {
        try {
            const response = await this.client.request<T>({
                method,
                url: path,
                data,
            });

            return response.data;
        } catch (error) {
            const axiosError = error as AxiosError<{ message: string }>;
            const paystackMessage =
                axiosError.response?.data?.message || axiosError.message;
            const statusCode = axiosError.response?.status || 500;

            throw new PaystackError(
                `Paystack API error (${statusCode}): ${paystackMessage}`,
                statusCode
            );
        }
    }
}

/**
 * Custom error class for Paystack API failures.
 * Carries the HTTP status code for appropriate error handling upstream.
 */
export class PaystackError extends Error {
    public statusCode: number;

    constructor(message: string, statusCode: number) {
        super(message);
        this.name = "PaystackError";
        this.statusCode = statusCode;
    }
}

export default new PaystackService();
